// Mirrors travelWallet.form and travelWallet.fields in the website locales.
// Examples are placeholders only, never initial form values.
const walletFormCopy = {
  'flight': (
    titleHint: 'Örn. İstanbul – Roma uçuşu',
    referenceLabel: 'PNR / rezervasyon kodu',
    referenceHint: 'Örn. TRV123',
    dateLabel: 'Kalkış tarihi',
    sectionTitle: 'Uçuş bilgileri',
    urlHint: 'havayolu.com/rezervasyonum',
    noteHint: 'Transfer, özel bagaj veya uçuş hatırlatması…',
  ),
  'stay': (
    titleHint: 'Örn. Roma merkez oteli',
    referenceLabel: 'Rezervasyon kodu',
    referenceHint: 'Örn. HTL456',
    dateLabel: 'Giriş tarihi',
    sectionTitle: 'Konaklama bilgileri',
    urlHint: 'otel.com/rezervasyonum',
    noteHint: 'Kahvaltı, giriş talebi veya resepsiyon notu…',
  ),
  'ticket': (
    titleHint: 'Örn. Kolezyum giriş bileti',
    referenceLabel: 'Bilet / sipariş kodu',
    referenceHint: 'Örn. BİLET-789',
    dateLabel: 'Etkinlik tarihi',
    sectionTitle: 'Bilet bilgileri',
    urlHint: 'bilet.com/siparisim',
    noteHint: 'Buluşma noktası veya giriş hatırlatması…',
  ),
  'insurance': (
    titleHint: 'Örn. Avrupa seyahat sigortası',
    referenceLabel: 'Poliçe numarası',
    referenceHint: 'Örn. POL-456789',
    dateLabel: 'Poliçe başlangıç tarihi',
    sectionTitle: 'Sigorta bilgileri',
    urlHint: 'sigorta.com/policem',
    noteHint: 'Kapsam veya acil durumda izlenecek adımlar…',
  ),
  'document': (
    titleHint: 'Örn. Pasaport bilgisi',
    referenceLabel: 'Belge referansı / son 4 hane',
    referenceHint: 'Tam belge numarasını kaydetme',
    dateLabel: 'Düzenlenme tarihi',
    sectionTitle: 'Belge bilgileri',
    urlHint: 'resmî doğrulama bağlantısı',
    noteHint: 'Belgenin kendisini ya da hassas bilgileri yazma…',
  ),
  'other': (
    titleHint: 'Örn. Havaalanı transferi',
    referenceLabel: 'Referans kodu',
    referenceHint: 'Varsa referans kodu',
    dateLabel: 'Tarih',
    sectionTitle: 'Ek bilgiler',
    urlHint: 'ilgili güvenli bağlantı',
    noteHint: 'İhtiyaç duyacağın kısa bir hatırlatma…',
  ),
};

const walletDetailCopy = {
  'airline': (label: 'Havayolu', hint: 'Örn. Türk Hava Yolları'),
  'flightNumber': (label: 'Uçuş numarası', hint: 'Örn. TK1861'),
  'origin': (label: 'Kalkış havalimanı', hint: 'Örn. İstanbul (IST)'),
  'destination': (label: 'Varış havalimanı', hint: 'Örn. Roma (FCO)'),
  'time': (label: 'Saat', hint: 'Saat seç'),
  'terminal': (label: 'Terminal', hint: 'Örn. Terminal 1'),
  'seat': (label: 'Koltuk', hint: 'Örn. 12A'),
  'baggage': (label: 'Bagaj hakkı', hint: 'Örn. 8 kg kabin + 20 kg'),
  'address': (label: 'Adres', hint: 'Otelin açık adresi'),
  'checkOut': (label: 'Çıkış tarihi', hint: 'Tarih seç'),
  'roomType': (label: 'Oda tipi', hint: 'Örn. Deluxe çift kişilik'),
  'contact': (label: 'İletişim telefonu', hint: 'Örn. +39 06 123 4567'),
  'venue': (label: 'Mekân', hint: 'Örn. Kolezyum ana girişi'),
  'gate': (label: 'Kapı / giriş', hint: 'Örn. B Kapısı'),
  'insurer': (label: 'Sigorta şirketi', hint: 'Örn. Allianz'),
  'endDate': (label: 'Poliçe bitiş tarihi', hint: 'Tarih seç'),
  'emergencyPhone': (
    label: 'Acil yardım telefonu',
    hint: 'Örn. +90 850 000 00 00',
  ),
  'documentType': (label: 'Belge türü', hint: 'Örn. Pasaport veya vize'),
  'expiryDate': (label: 'Son geçerlilik tarihi', hint: 'Tarih seç'),
  'issuer': (label: 'Düzenleyen kurum', hint: 'Örn. İstanbul Valiliği'),
};
